using System.Collections.Generic;

namespace SoundMist.Models.SoundCloud;

internal static class CountryCodes
{
    public static string GetCountryName(string? countryCode)
    {
        if (string.IsNullOrEmpty(countryCode))
            return string.Empty;

        if (_codes.TryGetValue(countryCode, out var country))
            return country;
        return "Unknown Country";
    }

    private static Dictionary<string, string> _codes = new()
    {
        { "DZ", "Algeria" },
        { "AO", "Angola" },
        { "AG", "Antigua And Barbuda" },
        { "BJ", "Benin" },
        { "BT", "Bhutan" },
        { "BW", "Botswana" },
        { "BF", "Burkina Faso" },
        { "BI", "Burundi" },
        { "CM", "Cameroon" },
        { "CV", "Cape Verde" },
        { "CF", "Central African Republic" },
        { "TD", "Chad" },
        { "KM", "Comoros" },
        { "CG", "Congo" },
        { "CD", "Democratic Republic of the Congo" },
        { "CI", "Cote d'Ivoire" },
        { "EG", "Egypt" },
        { "GQ", "Equatorial Guinea" },
        { "ER", "Eritrea" },
        { "ET", "Ethiopia" },
        { "GF", "French Guiana" },
        { "GA", "Gabon" },
        { "GM", "Gambia" },
        { "GH", "Ghana" },
        { "GN", "Guinea" },
        { "GW", "Guinea-Bissau" },
        { "KE", "Kenya" },
        { "LS", "Lesotho" },
        { "LR", "Liberia" },
        { "MW", "Malawi" },
        { "ML", "Mali" },
        { "MR", "Mauritania" },
        { "YT", "Mayotte" },
        { "MA", "Morocco" },
        { "MZ", "Mozambique" },
        { "NA", "Namibia" },
        { "NE", "Niger" },
        { "NG", "Nigeria" },
        { "QA", "Qatar" },
        { "RW", "Rwanda" },
        { "ST", "Sao Tome And Principe" },
        { "SN", "Senegal" },
        { "SC", "Seychelles" },
        { "SL", "Sierra Leone" },
        { "SO", "Somalia" },
        { "ZA", "South Africa" },
        { "SD", "Sudan" },
        { "SR", "Suriname" },
        { "SZ", "Swaziland" },
        { "TZ", "United Republic of Tanzania" },
        { "TG", "Togo" },
        { "TT", "Trinidad And Tobago" },
        { "UG", "Uganda" },
        { "EH", "Western Sahara" },
        { "ZM", "Zambia" },
        { "ZW", "Zimbabwe" },
        { "AF", "Afghanistan" },
        { "BH", "Bahrain" },
        { "BD", "Bangladesh" },
        { "IO", "British Indian Ocean Territory" },
        { "BN", "Brunei Darussalam" },
        { "KH", "Cambodia" },
        { "CN", "China" },
        { "DJ", "Djibouti" },
        { "HK", "Hong Kong" },
        { "IN", "India" },
        { "ID", "Indonesia" },
        { "IR", "Islamic Republic of Iran" },
        { "IQ", "Iraq" },
        { "IL", "Israel" },
        { "JP", "Japan" },
        { "JO", "Jordan" },
        { "KP", "Democratic People's Republic of Korea" },
        { "KR", "Republic of Korea" },
        { "KW", "Kuwait" },
        { "KG", "Kyrgyzstan" },
        { "LA", "Lao People's Democratic Republic" },
        { "LB", "Lebanon" },
        { "LY", "Libya" },
        { "MO", "Macao" },
        { "MY", "Malaysia" },
        { "MN", "Mongolia" },
        { "MM", "Myanmar" },
        { "NP", "Nepal" },
        { "OM", "Oman" },
        { "PK", "Pakistan" },
        { "PW", "Palau" },
        { "PS", "State of Palestine" },
        { "PH", "Philippines" },
        { "SA", "Saudi Arabia" },
        { "SG", "Singapore" },
        { "SB", "Solomon Islands" },
        { "SS", "South Sudan" },
        { "LK", "Sri Lanka" },
        { "SY", "Syrian Arab Republic" },
        { "TW", "Taiwan, Province of China" },
        { "TJ", "Tajikistan" },
        { "TH", "Thailand" },
        { "TL", "Timor-Leste" },
        { "TN", "Tunisia" },
        { "TR", "Turkey" },
        { "TM", "Turkmenistan" },
        { "AE", "United Arab Emirates" },
        { "UZ", "Uzbekistan" },
        { "VN", "Viet Nam" },
        { "YE", "Yemen" },
        { "AS", "American Samoa" },
        { "AU", "Australia" },
        { "CX", "Christmas Island" },
        { "CC", "Cocos (Keeling) Islands" },
        { "CK", "Cook Islands" },
        { "FJ", "Fiji" },
        { "PF", "French Polynesia" },
        { "HM", "Heard Island And McDonald Islands" },
        { "KI", "Kiribati" },
        { "MG", "Madagascar" },
        { "MV", "Maldives" },
        { "MH", "Marshall Islands" },
        { "MU", "Mauritius" },
        { "FM", "Federated States of Micronesia" },
        { "NR", "Nauru" },
        { "NC", "New Caledonia" },
        { "NZ", "New Zealand" },
        { "NU", "Niue" },
        { "MP", "Northern Mariana Islands" },
        { "PG", "Papua New Guinea" },
        { "WS", "Samoa" },
        { "TK", "Tokelau" },
        { "TO", "Tonga" },
        { "TV", "Tuvalu" },
        { "VU", "Vanuatu" },
        { "WF", "Wallis And Futuna" },
        { "AQ", "Antarctica" },
        { "AX", "Aaland Islands" },
        { "AL", "Albania" },
        { "AD", "Andorra" },
        { "AM", "Armenia" },
        { "AT", "Austria" },
        { "AZ", "Azerbaijan" },
        { "BY", "Belarus" },
        { "BE", "Belgium" },
        { "BA", "Bosnia And Herzegovina" },
        { "BV", "Bouvet Island" },
        { "BG", "Bulgaria" },
        { "HR", "Croatia" },
        { "CY", "Cyprus" },
        { "CZ", "Czech Republic" },
        { "DK", "Denmark" },
        { "EE", "Estonia" },
        { "FO", "Faroe Islands" },
        { "FI", "Finland" },
        { "FR", "France" },
        { "TF", "French Southern Territories" },
        { "GE", "Georgia" },
        { "DE", "Germany" },
        { "GI", "Gibraltar" },
        { "GR", "Greece" },
        { "GL", "Greenland" },
        { "GP", "Guadeloupe" },
        { "GG", "Guernsey" },
        { "VA", "Holy See (Vatican City State)" },
        { "HU", "Hungary" },
        { "IS", "Iceland" },
        { "IE", "Ireland" },
        { "IM", "Isle of Man" },
        { "IT", "Italy" },
        { "JE", "Jersey" },
        { "KZ", "Kazakhstan" },
        { "XK", "Kosovo" },
        { "LV", "Latvia" },
        { "LI", "Liechtenstein" },
        { "LT", "Lithuania" },
        { "LU", "Luxembourg" },
        { "MK", "North Macedonia" },
        { "MT", "Malta" },
        { "MQ", "Martinique" },
        { "MD", "Republic of Moldova" },
        { "MC", "Monaco" },
        { "ME", "Montenegro" },
        { "MS", "Montserrat" },
        { "NL", "Netherlands" },
        { "NF", "Norfolk Island" },
        { "NO", "Norway" },
        { "PL", "Poland" },
        { "PT", "Portugal" },
        { "RE", "Reunion" },
        { "RO", "Romania" },
        { "RU", "Russian Federation" },
        { "SH", "Saint Helena, Ascension And Tristan Da Cunha" },
        { "SM", "San Marino" },
        { "RS", "Serbia" },
        { "SX", "Sint Maarten (Dutch Part)" },
        { "SK", "Slovakia" },
        { "SI", "Slovenia" },
        { "GS", "South Georgia And The South Sandwich Islands" },
        { "ES", "Spain" },
        { "SJ", "Svalbard And Jan Mayen" },
        { "SE", "Sweden" },
        { "CH", "Switzerland" },
        { "UA", "Ukraine" },
        { "GB", "United Kingdom" },
        { "VG", "Virgin Islands, British" },
        { "AR", "Argentina" },
        { "AW", "Aruba" },
        { "BB", "Barbados" },
        { "BZ", "Belize" },
        { "BM", "Bermuda" },
        { "BO", "Plurinational State of Bolivia" },
        { "BQ", "Bonaire, Sint Eustatius And Saba" },
        { "BR", "Brazil" },
        { "CL", "Chile" },
        { "CO", "Colombia" },
        { "CR", "Costa Rica" },
        { "CU", "Cuba" },
        { "CW", "Curacao" },
        { "EC", "Ecuador" },
        { "SV", "El Salvador" },
        { "FK", "Falkland Islands (Malvinas)" },
        { "GD", "Grenada" },
        { "GT", "Guatemala" },
        { "GY", "Guyana" },
        { "HN", "Honduras" },
        { "JM", "Jamaica" },
        { "MX", "Mexico" },
        { "NI", "Nicaragua" },
        { "PA", "Panama" },
        { "PY", "Paraguay" },
        { "PE", "Peru" },
        { "PN", "Pitcairn" },
        { "PR", "Puerto Rico" },
        { "KN", "Saint Kitts And Nevis" },
        { "LC", "Saint Lucia" },
        { "UY", "Uruguay" },
        { "VE", "Bolivarian Republic of Venezuela" },
        { "AI", "Anguilla" },
        { "BS", "Bahamas" },
        { "CA", "Canada" },
        { "KY", "Cayman Islands" },
        { "DM", "Dominica" },
        { "DO", "Dominican Republic" },
        { "GU", "Guam" },
        { "HT", "Haiti" },
        { "BL", "Saint Barthelemy" },
        { "MF", "Saint Martin (French Part)" },
        { "PM", "Saint Pierre And Miquelon" },
        { "VC", "Saint Vincent And The Grenadines" },
        { "TC", "Turks And Caicos Islands" },
        { "US", "United States" },
        { "UM", "United States Minor Outlying Islands" },
        { "VI", "Virgin Islands, U.S." }
    };
}